// <copyright file="LinkCompulsoryCourses.cs" company="">
// Copyright (c) 2023 All Rights Reserved
// </copyright>
// <author>Gary Larson</author>
// <date>7/20/2023 5:06:20 PM</date>
// <summary>On create event of Student table, link Students to the compulsory courses of their University</summary>
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

using System;
using System.ServiceModel;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;

namespace CFA_Plugins.Plugins
{

    /// <summary>
    /// LinkCompulsoryCourses Plugin.
    /// </summary>    
    public class LinkCompulsoryCourses : PluginBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LinkCompulsoryCourses"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information.</param>
        public LinkCompulsoryCourses(string unsecure, string secure)
            : base(typeof(LinkCompulsoryCourses))
        {

            // TODO: Implement your custom configuration handling.
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// </remarks>
        protected override void ExecuteCdsPlugin(ILocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException(nameof(localContext));
            }
            // Obtain the tracing service
            ITracingService tracingService = localContext.TracingService;

            try
            {
                // Obtain the execution context from the service provider.  
                IPluginExecutionContext context = (IPluginExecutionContext)localContext.PluginExecutionContext;

                // Obtain the organization service reference for web service calls.  
                IOrganizationService currentUserService = localContext.CurrentUserService;

                // Implement your custom Plug-in business logic.
                if (context.InputParameters.Contains("Target") && context.InputParameters["Target"] is Entity)
                {
                    // Obtain the target entity from the input parameters.
                    Entity student = (Entity)context.InputParameters["Target"];

                    // Verify that the target entity represents a student.
                    if (student.LogicalName != "in23gl_student")
                        return;

                    // Get the university of the student
                    EntityReference studentUniversity = (EntityReference)student["in23gl_university"];

                    // Create a query to retrieve all compulsory courses of the same university
                    QueryExpression query = new QueryExpression
                    {
                        EntityName = "in23gl_course",
                        ColumnSet = new ColumnSet("in23gl_courseid"),
                        Criteria = new FilterExpression
                        {
                            Conditions =
                            {
                                new ConditionExpression
                                {
                                    AttributeName = "in23gl_iscompulsory",
                                    Operator = ConditionOperator.Equal,
                                    Values = { true }
                                },
                                new ConditionExpression
                                {
                                    AttributeName = "in23gl_university",
                                    Operator = ConditionOperator.Equal,
                                    Values = { studentUniversity.Id }
                                }
                            }
                        }
                    };

                    // Execute the query
                    EntityCollection compulsoryCourses = currentUserService.RetrieveMultiple(query);

                    // Link student with these courses
                    foreach (var course in compulsoryCourses.Entities)
                    {
                        currentUserService.Associate("in23gl_student", student.Id, new Relationship("in23gl_rel_Course_Student"), new EntityReferenceCollection { new EntityReference("in23gl_course", course.Id) });
                    }
                }

            }
            // Only throw an InvalidPluginExecutionException. Please Refer https://go.microsoft.com/fwlink/?linkid=2153829.
            catch (Exception ex)
            {
                tracingService?.Trace("An error occurred executing Plugin CFA_Plugins.Plugins.LinkCompulsoryCourses : {0}", ex.ToString());
                throw new InvalidPluginExecutionException("An error occurred executing Plugin CFA_Plugins.Plugins.LinkCompulsoryCourses .", ex);
            }
        }
    }
}
